### ISSUE TITLE
Inconsistent use of ConfigureAwait(false) in OidcClient causes deadlocks

### ISSUE THREAD

**Issue by VMelnalksnis** [IdentityModel/IdentityModel.OidcClient#362]
Using `OidcClient` from an application using a `SynchronizationContext`, for example an [Avalonia](https://github.com/AvaloniaUI/Avalonia) application, `RefreshTokenAsync` and most likely also other methods cause deadlocks, since `ConfigureAwait(false)` is not used for all awaits. It is possible to work around this using `Task.Run`. 

I'm ready to create a PR to add `ConfigureAwait(false)` for all async methods in `OidcClient` and used by it, unless I'm missing something and the current usage of async is intentional.

**Comment by leastprivilege** [comment]
Please create a PR. This sounds like an oversight.

**Comment by dIeGoLi** [comment]
@VMelnalksnis Could you maybe explain where exactly you are experiencing a deadlock? I took a quick look at RefreshTokenAsync and it seems fine to me. A deadlock normally occurs when you are doing something like `RefreshTokenAsync().Result` on the main thread/one synchronization context and the method executing switches to another synchronization context but then can not switch back because the method is not awaited using await but synchronously blocks the thread by for example using `.Result`.

**Comment by VMelnalksnis** [comment]
I was experiencing issues in event handlers, and was using `GetAwaiter().GetResult()`. As I understand, except for avoiding them completely, there is no good way to use async in events - it's either `async void`, `.Result` or `Task.Run()` to avoid deadlocks. Since I used `RefreshTokenAsync()` in a `DelegatingHandler`, it can be called anywhere I'm using that http client.

For `LoginAsync` I didn't consider that `IBrowser` could be implemented using an integrated browser, since I was using something similar to [SystemBrowser.cs](clients/ConsoleClientWithBrowser/SystemBrowser.cs). However, it seems to me that `RefreshTokenAsync()` does not use `IBrowser` or any other user-defined async methods/delegates, only HTTP calls. Would it be ok to add `ConfigureAwait(false)` only in `RefreshTokenAsync()`, or am I also missing something there?

**Comment by dIeGoLi** [comment]
A lot of times for events it's fine to be async void, since you do not need to await them. If you need to be able to wait synchronously, you need to use Task.Run: `Task.Run(method).GetAwaiter().GetResult()`

Since you are using a delegating handler to refresh the token. Are you aware that the `LoginResult` offers a property `RefreshTokenHandler` which is a [RefreshTokenDelegatingHandler](https://github.com/IdentityModel/IdentityModel.OidcClient/blob/46d7b25cd71eb0be5f3c203c2525b1f357e408db/src/OidcClient/RefreshTokenDelegatingHandler.cs)
You can use that one in your http client. Never had problems with it.

I think it would be ok to add ConfigureAwait(false) only in RefreshTokenAsync. But i think the problem at it's root is using GetAwaiter().GetResult() in a non async method without using Task.Run. You can never know what thread switches the call path of a library will perform and therefore will always be a possibilty to a deadlock if you wait synchronously without using Task.Run. And as well i am not convinced that only adding ConfigureAwait(false) really solves your problem, because normally ConfigureAwait(false) causes the problem but not solving it, since it's the reason that a switch to the main thread is necessary and results in a deadlock.

**Comment by VMelnalksnis** [comment]
I tested the version with `ConfigureAwait(false)` and removing the `Task.Run` I was using as a workaround, and it fixed the issue. As I understand from [this](https://devblogs.microsoft.com/dotnet/configureawait-faq/#when-should-i-use-configureawaitfalse), unless a delegate can be passed in, like in `LoginAsync` via `IBrowser.InvokeAsync`, `ConfigureAwait(false)` should be used in libraries. But I agree, I it would probably be best to just change my approach and try to avoid `.Result/.GetAwaiter().GetResult()` anyway if it will continue causing problems like this. 

I'm aware of the provided handler, however I didn't see a straightforward way to use it with `IServiceCollection`, and I also need to support non-OIDC authentication.
