### ISSUE TITLE
Annotate .Net 6 Assembly As Trimmable 

### ISSUE THREAD

**Issue by mwasplund** [IdentityModel/IdentityModel.OidcClient#390]
As of .Net 6 assemblies can be annotated with the IsTrimmable property. This will enable warnings for publish as trimmed issues. Once all of these issues are addressed or annotated as RequireUnreferencedCode the downstream consumer can publish their final executable with all unused code trimmed out.

https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

**Comment by enclave-alistair** [comment]
Just to note that this issue, when building for net8, meant I got the error:

```
Reflection-based serialization has been disabled for this application
```

when using the NoValidationIdentityTokenValidator. This is because the trimmed publish defaults for System.Text.Json in net8 have changed to fail on attempts to use reflection serialisation.

I had to manually copy the patched code from #391; eagerly awaiting the release of the changes in that PR.
